# Generated by Django 4.0.6 on 2022-07-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
